GET http://localhost:3000/api/doc

###
POST http://localhost:3000/api/doc 
Content-Type: application/json

{
"title": "First Ever Doc", "content": ""
}

###
PUT http://localhost:3000/edit/622feee4ab01d44d4cb0543e
Content-Type:  application/json

{
    "content": ""
}

###
GET http://localhost:3000/api/dir/62486fa29e951c280ec251d2

###
PATCH http://localhost:3000/api/dir/62486fa29e951c280ec251d2
Content-Type:  application/json

{
    "docs": ["But now we have to adjust"]
}