GET http://localhost:3000/api/doc

###
POST http://localhost:3000/api/dir
Content-Type: application/json

{
    "title": "New Thing 2", 
    "docs": [],
    "dirs": [],
    "parent": "62572b15aab30f9636a38ed9"
}

###
PATCH  http://localhost:3000/api/dir/

###
DELETE http://localhost:3000/api/dir/